name    'kayak-r9util'
version '0.0.4'
source  'git://github.com/kayakco/r9util.git'
author  'kayak'
license 'Apache License, Version 2.0'
summary 'Misc utilities'
description 'Misc utilities used in KAYAK Puppet modules'
project_page 'https://github.com/kayakco/r9util'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
